apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  namespace: 3tier-app
data:
  DATABASE_URL: "postgresql://postgres:postgres@postgres:5432/todo_db?schema=public"
  BACKEND_URL: "http://backend:4000"
  FRONTEND_URL: "http://frontend:3000"
