apiVersion: batch/v1
kind: Job
metadata:
  name: prisma-db-push
  namespace: 3tier-app
spec:
  template:
    spec:
      containers:
        - name: prisma
          image: your-dockerhub-username/3tierapp_backend:latest
          command: ["npx", "prisma", "db", "push"]
          env:
            - name: DATABASE_URL
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: DATABASE_URL
      restartPolicy: Never
  backoffLimit: 1
